### ISSUE TITLE
create maru-0.7 branch

### ISSUE THREAD

**Issue by pintaf** [maruos/vendor_maruos_packages_apps_MaruSettings#1]
Hello @utzcoz 

As you are aware of, I am working on porting maru to LOS16.
I am reaching the end of the port and start to have something working.

I am currently having issues with maru running mcprepare on first boot, while it runs fine once booted.
Instead of loosing time on that, I think it would be better to download the image we want (debian, ubuntu) and then run mcprepare on this image. We could even imagine having multiple images/containers side by side.

All this should be managed in the settings.
This is why I looked at your repo.
First of all, I have to congrats you, it's a very good job. I have been able to integrate it into my build of maru 0.7 for pme (HTC10).
You can find the build [here](https://mega.nz/file/rQgjFLYA#OvfRonHirOCh1K4p8xBa0i6vvLIPjUXpgis138ohaT8).

It has been built thx to the manifest found [here](https://github.com/pintaf/manifest) (branch maru-0.7)

In the build I mention, I have integrated both your settings and the normal maru settings. Currently to know if you are in the normal maru settings, you car check what is written (if it's UNI-OS) as seen [here](https://groups.google.com/g/maru-os-dev/c/WZB-oWXDFiE/m/2fG6KtoYBwAJ), then you are in the "normal" maru settings. However if you see written "maru os", then you are in your version of settings.

With the assumption that mcprepare has been ran correctly, here is what I observe with your settings:
I can start the container, but once started, the switch stays grayed out and no way to stop the container. If we go in the "normal" settings however, this is possible. 
This has been done with desktop running in bg (no screen connected). With screen connected, I could see the desktop, but I also had issues with your version of settings.

But it seems quite close to be working.

Here are what I changed:
This is [my base work](https://github.com/pintaf/vendor_maruos_packages_apps_MaruSettings), a fork of your repo (do not pay attention to the branch name maru-0.6, it is actually for maru-0.7 LOS16, I just didn't take the time to change that).
I needed to make some adjustments to make it work with LOS16 / android 9.
First, I removed all references to support libraries, as we build on recent SDK. That may be the source of some problems, I haven't tried again with them added back. I also added this flag: LOCAL_PRIVATE_PLATFORM_APIS := true

final I made some modifications to the build system as per your instructions.
However, I needed to add more changes ([1](https://github.com/pintaf/vendor_maruos/commit/f8363c44986f38df02b02f322ee5362bf857c284#diff-4162fe434e541fbdf5a42a77eb0b0d88), [2](https://github.com/pintaf/vendor_maruos/commit/e43c92ff682702500f94f383721aebc245ab0fc0#diff-95c957050a4b8b03617c159caaec8b1d)) to cope with android 9 new permissions [requirements](https://source.android.com/devices/tech/config/perms-whitelist) for priv-apps.

You say
> We use SettingsLib as library to create setting view. This library needs some runtime permissions to query user information. So we add the shared uid android.uid.system to skip the system checking for critic operations. Maybe we should assign the permission to the app from config file to replace shared uid.

Maybe this is not necessary anymore now.

So, my requests:
- create a maru-0.7 branch and maybe add me as contributor to your repo, it would be better than working on different forks.
- Are you willing to continue working on this and help me solve the problems on maru-0.7 ?
- We could implement the download of customs images and extract, freeing some space on system partition, and enabling more options.

**Comment by utzcoz** [comment]
> create a maru-0.7 branch and maybe add me as contributor to your repo, it would be better than working on different forks

Branch `maru-0.7` has been created, and I invite you as collaborator from GitHub. You can push code to maru-0.7 directly. If you want to push code to `maru-0.6`, maybe you can add me as reviewer.

> Are you willing to continue working on this and help me solve the problems on maru-0.7 ?

No problem. I only have pixel/pixel xl, maybe I can test it with `maru-0.6`, because the code bases are similar. If need, I can port pixel/pixel xl to `maru-0.7`. Actually, I want to wait official `maru-0.7`.  Maybe you can discuss with @pdsouza to merge porting to official repo.

> We could implement the download of customs images and extract, freeing some space on system partition, and enabling more options.

Yes, these features are considered to be implemented before, and maybe it's time to try to implement it.
And lastly, thanks your interest in this project.

**Comment by utzcoz** [comment]
> I also added this flag: LOCAL_PRIVATE_PLATFORM_APIS := true

From the Android 9, if the project uses the system hidden API, we should add `LOCAL_PRIVATE_PLATFORM_APIS := true` to `Android.mk` to skip build system link_type validation. I have wrote an article to introduce it: [Introduce link_type in AOSP build system](https://utzcoz.github.io/aosp/2020/03/19/Introduce-link_type-in-AOSP-build-system.html). Hope it will be useful.

**Comment by pdsouza** [comment]
@pintaf @utzcoz Thanks for coordinating your work on this guys!
