### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by utzcoz** [maruos/vendor_maruos_packages_apps_MaruSettings#6]
It's better there are Chinese translation for MaruSettings setting items.

**Comment by utzcoz** [comment]
Hi @pintaf , could you help to add French translation?

**Comment by pdsouza** [comment]
Translations would be great! I know we have a lot of Maru users in Germany and Japan too. Maybe we can reach out on our forum and see if anyone is interested in helping with translations.

**Comment by pintaf** [comment]
I can do French and Spanish.
I'll try to do that when I get some time.

**Comment by utzcoz** [comment]
I added zh-rCN, zh-rHK, zh-rTW. And it works fine after changing system language and rebooting system. There is a problem that the text doesn't change language after changing system language. I will create a new issue to track it.

**Comment by utzcoz** [comment]
https://github.com/maruos/vendor_maruos_packages_apps_MaruSettings/issues/9 The new issue is here.

**Comment by pdsouza** [comment]
So cool!
