### ISSUE TITLE
Add Java checkstyle checking for MaruSettings

### ISSUE THREAD

**Issue by utzcoz** [maruos/vendor_maruos_packages_apps_MaruSettings#7]
Although we can't build MaruSettings with gradle now, we can use checkstyle script to check Java code style that doesn't need full building, and add it to GitHub actions to check later commits. We can use [google-java-format](https://github.com/google/google-java-format) with [AOSP codestyle](https://github.com/google/google-java-format/blob/5104d0b27888f3bfab7113f5606374cda5632102/scripts/google-java-format-diff.py#L56).

**Comment by utzcoz** [comment]
cc @pdsouza @pintaf .

**Comment by pdsouza** [comment]
Good idea. Anything that can be automated will help us move faster.
